.TH IOTO "1" "June 2022" "ioto" "User Commands"
.SH NAME
ioto\- Embedded Device Agent
.SH SYNOPSIS
.B ioto [options]
.br
.B ioto [options]
.P
.B ioto
    \fB--background\fR
    \fB--debug\fR
    \fB--home directory\fR
    \fB--profile profile\fR
    \fB--timeouts\fR
    \fB--trace file[:type:source]\fR
    \fB--verbose\fR
    \fB--version\fR
.SH DESCRIPTION
Ioto is a compact device agent that includes an MQTT client, HTTP web server, HTTP client and integration with AWS IoT. It can run as a stand-alone as a device agent or
the Ioto library can be embedded in applications.
.P
The Ioto web server supports HTTP/1.0, HTTP/1.1, TLS, user authentication, sessions, chunked transfers, file upload, and security limits.
.P
Ioto normally reads a set of JSON configuration files. It reads the \fBconfig.json5\fR file for general configuration, the \fBweb.json5\fR for web server configuration, \fBauth.json5\fR for authentication configuration, and \fBshadow.json5\fR for persisted device shadow state.
.P
Ioto can trace activities to a file that defaults to 'stdout'. This can be modified via the --trace command line option.
.P
The --trace option specifies a destination file for trace messages. This will override the trace property in the Ioto config.json5 file. The trace argument syntax is fileName[:types:sources]. The types are a comma separated list of message types. Valid types include: info, debug, error, and trace. Sources are the code module names originating the trace messages. You can use "all" for types and sources to match all types/sources. You can also use "!type" and "!source" to negate a type or source.
.P
Ioto responds to the SIGUSR2 signal and increases the trace level.
.SH OPTIONS
.TP
\fB\--background\fR
Run Ioto in the background and detach from the console.
.TP
\fB\--debug\fR
Enable debug tracing. The \fB-T\fR option is an alias for --tracing.
.TP
\fB\--home directory\fR
Change to the specified directory before running Ioto.
.TP
\fB\--trace file[:types:sources]\fR
Name the Ioto trace file. The types are a comma separated list of message types. Valid types include: info, debug, error, and trace. Sources are the code module names originating the trace messages. You can use "all" for types and sources to match all types/sources. You can also use "!type" and "!source" to negate a type or source.
.TP
\fB\--profile profile\fR
Select the operational profile. Defaults to "prod".
.TP
\fB\--timeouts\fR
Run Ioto in debug mode and disable all timeouts. This disables request and session timeouts.
.TP
\fB\--verbose\fR
Run with more verbose tracing.
.TP
\fB\--version\fR
Output the product version number.
.PP
.SH FILES
.PD 0
.B /etc/ioto
.br
.B /var/www/ioto
.br
.B /usr/local/lib/ioto
.br
.br
.PD
.SH "REPORTING BUGS"
Report bugs to dev@embedthis.com.
.SH COPYRIGHT
Copyright (c) Embedthis Software.
.br
.SH "SEE ALSO"
pass
